package connector

import (
	v2 "github.com/conductorone/baton-sdk/pb/c1/connector/v2"
	"github.com/conductorone/baton-sdk/pkg/annotations"
)

// Datadog permission names from https://docs.datadoghq.com/account_management/rbac/permissions/
func capabilityPermissions(perms ...string) *v2.CapabilityPermissions {
	cp := &v2.CapabilityPermissions{}
	for _, p := range perms {
		cp.Permissions = append(cp.Permissions, &v2.CapabilityPermission{Permission: p})
	}
	return cp
}

var (
	// userResourceType is registered on every install (connector.go), so its
	// advertised permissions must be the ones the always-on user sync and
	// account provisioning actually call: user_access_invite for CreateUser,
	// user_access_manage for UpdateUser/DisableUser.
	//
	// service_account_write is deliberately NOT listed here even though
	// userResourceType carries CAPABILITY_CREDENTIAL_ISSUE. Issuance only
	// exists when sync-secrets is on -- that is the flag that swaps
	// credentialUserBuilder in for userBuilder and registers
	// applicationKeyBuilder at all -- so listing it here would tell every
	// sync-secrets-off install to grant a Datadog Admin permission that no
	// code path in that configuration can reach.
	//
	// baton_capabilities.json cannot express "only when sync-secrets is on":
	// it is one static document, generated by `./connector capabilities` from
	// a connector built with SyncSecrets and SyncSchedules forced true (see
	// cmd/baton-datadog/main.go), and CapabilityPermissions has no
	// conditional form. Scoping the permission to the resource type that only
	// exists under the flag is therefore how the conditionality is carried:
	// service_account_write lives on serviceAccountApplicationKeyResourceType,
	// which is only registered when sync-secrets is on, and the user type's
	// credential_issue block points at that type via secretResourceTypeId, so
	// the requirement is still discoverable from the metadata.
	userResourceType = &v2.ResourceType{
		Id:          "user",
		DisplayName: "User",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_USER},
		Annotations: annotations.New(
			&v2.SkipEntitlementsAndGrants{},
			capabilityPermissions(
				"user_access_invite",
				"user_access_manage",
			),
		),
	}
	roleResourceType = &v2.ResourceType{
		Id:          "role",
		DisplayName: "Role",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_ROLE},
		Annotations: annotations.New(
			capabilityPermissions("user_access_manage"),
		),
	}
	teamResourceType = &v2.ResourceType{
		Id:          "team",
		DisplayName: "Team",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_GROUP},
		Annotations: annotations.New(
			capabilityPermissions("user_access_manage"),
		),
	}
	// apiTokenResourceType covers organization-scoped API keys (Datadog's
	// "API keys", /api/v2/api_keys): org-wide credentials not owned by any
	// single Datadog identity. This connector still syncs and can delete
	// them, but Issue no longer targets this type -- an org-scoped key
	// issued on behalf of a selected user is not an honest mapping of who
	// holds it. See serviceAccountApplicationKeyResourceType for the type
	// Issue does target.
	//
	// The advertised permissions are the ones Datadog's own API spec marks
	// required (the per-operation "x-permission" block) for the only two
	// endpoints the advertised capabilities call: ListAPIKeys, backing
	// CAPABILITY_SYNC, requires api_keys_read, and DeleteAPIKey
	// (DELETE /api/v2/api_keys/{api_key_id}), backing
	// CAPABILITY_RESOURCE_DELETE, requires api_keys_delete. api_keys_delete
	// is a real Datadog permission ("API Keys Delete -- Delete API Keys for
	// your organization", Datadog Admin Role) and is the one that governs
	// delete; api_keys_write is scoped to CreateAPIKey/UpdateAPIKey ("Create
	// and rename API Keys") and is deliberately NOT advertised here, because
	// no advertised capability on this type creates or renames a key.
	// Advertising it would make C1 demand org-wide key-creation rights the
	// connector never exercises. CreateAPIKey/FindAPIKeyByName remain on
	// DatadogClient for tests.
	apiTokenResourceType = &v2.ResourceType{
		Id:          "api-key",
		DisplayName: "Organization API Key",
		Description: "A Datadog organization API key. Owned by the org, not by any single Datadog identity; not used for credential issuance by this connector.",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_SECRET},
		Annotations: annotations.New(
			&v2.SkipEntitlementsAndGrants{},
			capabilityPermissions("api_keys_read", "api_keys_delete"),
		),
	}
	// serviceAccountApplicationKeyResourceType covers application keys owned
	// by a Datadog service-account user (/api/v2/service_accounts/{id}/application_keys).
	// This is the resource type credential issuance targets: the key is
	// scoped to and owned by one service-account identity, so a synced
	// resource of this type is distinguishable from an apiTokenResourceType
	// (organization API key) by resource type id, display name, and the
	// underlying SecretTrait's credential_detail (see application_key.go).
	//
	// Every service-account application-key endpoint this connector calls
	// requires exactly one Datadog RBAC permission, service_account_write:
	// ListServiceAccountApplicationKeys (sync),
	// CreateServiceAccountApplicationKey (issue) and
	// DeleteServiceAccountApplicationKey (revoke). This is the "x-permission"
	// block Datadog publishes for each operation in its own OpenAPI spec
	// (docs.datadoghq.com/resources/json/full_spec_v2.json, the spec that
	// renders the public API reference); Datadog's role-permission page
	// describes the permission as "Create, disable, and use Service Accounts
	// in your organization" (Datadog Admin Role).
	//
	// Only service_account_write is advertised, not user_access_manage as
	// well, and that is deliberate. The spec's x-permission lists are OR
	// lists that do name several accepted permissions when several are
	// accepted -- DisableUser and UpdateUser, for instance, accept
	// user_access_manage OR service_account_write. For the application-key
	// operations the list has exactly one entry, so user_access_manage is not
	// an accepted alternative and advertising it would send operators after a
	// permission the API will not honour for these calls.
	//
	// user_access_manage does appear in Datadog's AuthZ oauth2 scope list,
	// which is a different axis from RBAC and does not apply here: this
	// connector authenticates with apiKeyAuth + appKeyAuth, and every value
	// in this file is an RBAC permission id. service_account_write is not an
	// OAuth scope at all, so an OAuth-scope reading of these endpoints will
	// disagree with this annotation by design.
	serviceAccountApplicationKeyResourceType = &v2.ResourceType{
		Id:          "service-account-application-key",
		DisplayName: "Service Account Application Key",
		Description: "A Datadog application key owned by one service-account identity. Distinct from an org API key (\"api-key\"): scoped to, and deleted through, its owning service account.",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_SECRET},
		Annotations: annotations.New(
			&v2.SkipEntitlementsAndGrants{},
			capabilityPermissions("service_account_write"),
		),
	}
	scheduleResourceType = &v2.ResourceType{
		Id:          "schedule",
		DisplayName: "Schedule",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_GROUP},
		Annotations: annotations.New(
			capabilityPermissions("on_call_read"),
		),
	}
)
