package connector

import (
	v2 "github.com/conductorone/baton-sdk/pb/c1/connector/v2"
	"github.com/conductorone/baton-sdk/pkg/annotations"
)

// Datadog permission names from https://docs.datadoghq.com/account_management/rbac/permissions/
func capabilityPermissions(perms ...string) *v2.CapabilityPermissions {
	cp := &v2.CapabilityPermissions{}
	for _, p := range perms {
		cp.Permissions = append(cp.Permissions, &v2.CapabilityPermission{Permission: p})
	}
	return cp
}

var (
	// userResourceType is registered on every install (connector.go), so its
	// advertised permissions must be the ones the always-on user sync and
	// account provisioning actually call: user_access_invite for CreateUser,
	// user_access_manage for UpdateUser/DisableUser.
	//
	// service_account_write is deliberately NOT listed here even though
	// userResourceType carries CAPABILITY_CREDENTIAL_ISSUE. Issuance only
	// exists when sync-secrets is on -- that is the flag that swaps
	// credentialUserBuilder in for userBuilder and registers
	// applicationKeyBuilder at all -- so listing it here would tell every
	// sync-secrets-off install to grant a Datadog Admin permission that no
	// code path in that configuration can reach.
	//
	// baton_capabilities.json cannot express "only when sync-secrets is on":
	// it is one static document, generated by `./connector capabilities` from
	// a connector built with SyncSecrets and SyncSchedules forced true (see
	// cmd/baton-datadog/main.go), and CapabilityPermissions has no
	// conditional form. Scoping the permission to the resource type that only
	// exists under the flag is therefore how the conditionality is carried:
	// service_account_write lives on serviceAccountApplicationKeyResourceType,
	// which is only registered when sync-secrets is on, and the user type's
	// credential_issue block points at that type via secretResourceTypeId, so
	// the requirement is still discoverable from the metadata.
	userResourceType = &v2.ResourceType{
		Id:          "user",
		DisplayName: "User",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_USER},
		Annotations: annotations.New(
			&v2.SkipEntitlementsAndGrants{},
			capabilityPermissions(
				"user_access_invite",
				"user_access_manage",
			),
		),
	}
	roleResourceType = &v2.ResourceType{
		Id:          "role",
		DisplayName: "Role",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_ROLE},
		Annotations: annotations.New(
			capabilityPermissions("user_access_manage"),
		),
	}
	teamResourceType = &v2.ResourceType{
		Id:          "team",
		DisplayName: "Team",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_GROUP},
		Annotations: annotations.New(
			capabilityPermissions("user_access_manage"),
		),
	}
	// apiTokenResourceType covers organization-scoped API keys (Datadog's
	// "API keys", /api/v2/api_keys): org-wide credentials not owned by any
	// single Datadog identity. Issue targets this type only when the operator
	// grants allow-org-api-key-deletion -- an org-scoped key has no honest
	// owner, and the SDK will not advertise an issuance option whose secret
	// resource type has no revoke path. See
	// serviceAccountApplicationKeyResourceType for the type Issue prefers.
	//
	// The advertised permissions are the ones Datadog's own API spec marks
	// required (the per-operation "x-permission" block) for the endpoints the
	// advertised capabilities call. api_keys_read backs CAPABILITY_SYNC
	// (ListAPIKeys) and is always advertised. api_keys_write backs CreateAPIKey
	// and so is advertised only by deletableAPITokenResourceType, which is also
	// the only variant that can be an issuance target. api_keys_delete backs
	// CAPABILITY_RESOURCE_DELETE (DeleteAPIKey) and is likewise only advertised
	// on that variant: this base type carries no delete path, so demanding a
	// Datadog Admin permission for it would send operators after rights no
	// reachable code exercises.
	apiTokenResourceType = newAPITokenResourceType("api_keys_read")
	// deletableAPITokenResourceType is apiTokenResourceType as registered when
	// allow-org-api-key-deletion is on: same id, plus the permissions the
	// delete and issue paths that grant unlocks actually require.
	// api_keys_delete is "API Keys Delete -- Delete API Keys for your
	// organization" and api_keys_write is "Create and rename API Keys", both
	// Datadog Admin Role permissions.
	deletableAPITokenResourceType = newAPITokenResourceType("api_keys_read", "api_keys_write", "api_keys_delete")
	// serviceAccountApplicationKeyResourceType covers application keys owned
	// by a Datadog service-account user (/api/v2/service_accounts/{id}/application_keys).
	// This is the resource type credential issuance targets: the key is
	// scoped to and owned by one service-account identity, so a synced
	// resource of this type is distinguishable from an apiTokenResourceType
	// (organization API key) by resource type id, display name, and the
	// underlying SecretTrait's credential_detail (see application_key.go).
	//
	// The service-account-scoped endpoints this connector calls require one
	// Datadog RBAC permission, service_account_write:
	// ListServiceAccountApplicationKeys (sync),
	// CreateServiceAccountApplicationKey (issue) and
	// DeleteServiceAccountApplicationKey (revoke). Revoke also reaches one
	// org-scoped endpoint, GetApplicationKey, to recover the owning service
	// account when the caller does not supply it; that one is governed by
	// org_app_keys_read, so both are advertised. A role holding only
	// service_account_write still syncs and issues -- it fails just the
	// owner lookup, and reports PermissionDenied naming it. These are the
	// "x-permission"
	// block Datadog publishes for each operation in its own OpenAPI spec
	// (docs.datadoghq.com/resources/json/full_spec_v2.json, the spec that
	// renders the public API reference); Datadog's role-permission page
	// describes the permission as "Create, disable, and use Service Accounts
	// in your organization" (Datadog Admin Role).
	//
	// Only service_account_write is advertised, not user_access_manage as
	// well, and that is deliberate. The spec's x-permission lists are OR
	// lists that do name several accepted permissions when several are
	// accepted -- DisableUser and UpdateUser, for instance, accept
	// user_access_manage OR service_account_write. For the application-key
	// operations the list has exactly one entry, so user_access_manage is not
	// an accepted alternative and advertising it would send operators after a
	// permission the API will not honour for these calls.
	//
	// user_access_manage does appear in Datadog's AuthZ oauth2 scope list,
	// which is a different axis from RBAC and does not apply here: this
	// connector authenticates with apiKeyAuth + appKeyAuth, and every value
	// in this file is an RBAC permission id. service_account_write is not an
	// OAuth scope at all, so an OAuth-scope reading of these endpoints will
	// disagree with this annotation by design.
	serviceAccountApplicationKeyResourceType = &v2.ResourceType{
		Id:          "service-account-application-key",
		DisplayName: "Service Account Application Key",
		Description: "A Datadog application key owned by one service-account identity. Distinct from an org API key (\"api-key\"): scoped to, and deleted through, its owning service account.",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_SECRET},
		Annotations: annotations.New(
			&v2.SkipEntitlementsAndGrants{},
			capabilityPermissions("service_account_write", "org_app_keys_read"),
		),
	}
	scheduleResourceType = &v2.ResourceType{
		Id:          "schedule",
		DisplayName: "Schedule",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_GROUP},
		Annotations: annotations.New(
			capabilityPermissions("on_call_read"),
		),
	}
)

// newAPITokenResourceType builds the organization API key resource type with a
// given permission set. The id is shared across variants because only one of
// them is ever registered: which one depends on allow-org-api-key-deletion.
func newAPITokenResourceType(permissions ...string) *v2.ResourceType {
	return &v2.ResourceType{
		Id:          "api-key",
		DisplayName: "Organization API Key",
		Description: "A Datadog organization API key. Owned by the org, not by any single Datadog identity.",
		Traits:      []v2.ResourceType_Trait{v2.ResourceType_TRAIT_SECRET},
		Annotations: annotations.New(
			&v2.SkipEntitlementsAndGrants{},
			capabilityPermissions(permissions...),
		),
	}
}
