name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  sync-test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_API_KEY: ${{ secrets.BATON_API_KEY }}
      BATON_APP_KEY: ${{ secrets.BATON_APP_KEY }}
      BATON_SITE: ${{ secrets.BATON_SITE }}
      BATON_SYNC_SECRETS: true
      BATON_SYNC_SCHEDULES: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build baton-datadog
        run: go build ./cmd/baton-datadog
      - name: Test sync
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-datadog
          baton-entitlement: 'role:32949318-6c01-11f1-94df-da7ad0900005:member'
          baton-principal: 'a7765c65-e68c-4e8e-8c96-10f0c9794db2'
          baton-principal-type: 'user'
